openapi: 3.0.0
info:
  title: Physical AI & Humanoid Robotics Book RAG API
  description: API for the RAG (Retrieval-Augmented Generation) system that powers the book's chatbot
  version: 1.0.0
  contact:
    name: Book Development Team
    email: dev@physicalai-book.com

servers:
  - url: https://api.physicalai-book.com/v1
    description: Production server
  - url: https://staging-api.physicalai-book.com/v1
    description: Staging server
  - url: http://localhost:8000
    description: Local development server

paths:
  /query:
    post:
      summary: Query the RAG system with a question
      description: Submit a question to the RAG system and receive an answer based on book content
      operationId: queryBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response with answer and sources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Health check
      description: Check the health status of the RAG API
      operationId: healthCheck
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /ingest:
    post:
      summary: Ingest book content
      description: Ingest new book content into the vector store
      operationId: ingestContent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestRequest'
      responses:
        '200':
          description: Content successfully ingested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestResponse'
        '400':
          description: Invalid content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - question
      properties:
        question:
          type: string
          description: The question to ask about the book content
          example: "Explain how ROS 2 nodes communicate with each other"
        context:
          type: string
          description: Optional context to narrow the search (e.g., "module-1-ros")
          example: "module-1-ros"
        maxResults:
          type: integer
          description: Maximum number of results to return (default 5)
          default: 5
          minimum: 1
          maximum: 10
        groundingThreshold:
          type: number
          description: Minimum grounding score for including results (default 0.7)
          default: 0.7
          minimum: 0.0
          maximum: 1.0

    QueryResponse:
      type: object
      required:
        - answer
        - sources
        - groundingScore
      properties:
        answer:
          type: string
          description: The answer generated by the LLM based on book content
          example: "ROS 2 nodes communicate through topics using a publish-subscribe pattern..."
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
          description: List of sources used to generate the answer
        groundingScore:
          type: number
          description: Confidence score for the grounding of the answer to book content
          minimum: 0.0
          maximum: 1.0
          example: 0.92

    Source:
      type: object
      required:
        - chapterId
        - chapterTitle
        - content
        - relevanceScore
      properties:
        chapterId:
          type: string
          description: Unique identifier for the chapter
          example: "mod1-ch3-ros-nodes"
        chapterTitle:
          type: string
          description: Title of the chapter
          example: "ROS 2 Nodes"
        content:
          type: string
          description: The content chunk that was used as a source
          example: "In ROS 2, nodes are the fundamental units of computation..."
        relevanceScore:
          type: number
          description: How relevant this source was to the query
          minimum: 0.0
          maximum: 1.0
          example: 0.89

    IngestRequest:
      type: object
      required:
        - content
        - chapterId
      properties:
        content:
          type: string
          description: The book content to be ingested
          example: "Chapter 1: Introduction to ROS 2. ROS 2 (Robot Operating System 2) is..."
        chapterId:
          type: string
          description: Unique identifier for the chapter
          example: "mod1-ch1-intro"
        chapterTitle:
          type: string
          description: Title of the chapter
          example: "Introduction to ROS 2"
        metadata:
          type: object
          description: Additional metadata about the content
          additionalProperties: true

    IngestResponse:
      type: object
      required:
        - success
        - chunkCount
      properties:
        success:
          type: boolean
          description: Whether the ingestion was successful
          example: true
        chunkCount:
          type: integer
          description: Number of content chunks created
          example: 12
        chunkIds:
          type: array
          items:
            type: string
          description: IDs of the created chunks
          example: ["chunk1", "chunk2", "chunk3"]

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          description: Health status
          enum: [healthy, degraded, unavailable]
          example: healthy
        timestamp:
          type: string
          format: date-time
          description: Time of the health check
          example: "2023-10-20T10:00:00Z"
        details:
          type: object
          description: Additional health details
          additionalProperties: true

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "BAD_REQUEST"
        message:
          type: string
          description: Human-readable error message
          example: "The request body is invalid"
        details:
          type: object
          description: Additional error details (optional)
          additionalProperties: true

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication

security:
  - ApiKeyAuth: []

tags:
  - name: query
    description: Query the RAG system
  - name: ingestion
    description: Content ingestion operations
  - name: health
    description: Health check endpoints